### PR TITLE
updater: fix systemd, switch to oneshot

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Comment by coop182** [comment]
@aptalca after this change my system now hangs on boot, I think it’s getting to the sleep 600 command where as previously it was not?

**Comment by aptalca** [comment]
Can you open an issue please? I'll take a look in a bit @coop182

**Comment by aptalca** [comment]
@coop182 fixed here: #79

**Comment by coop182** [comment]
Thanks @aptalca

**Pull request merged**
